### PR TITLE
fix(jsx-email): add link href to vml for outlook buttons

### LINKED ISSUE #272: Outlook classic: Buttons are not actually clickable
- Component or Package Name: jsx-email
- Component or Package Version: 2.5.4
- `@jsxp-email/cli` Version?: whatever came with it
- Operating System (or Browser): Server running on Mac OSX (during dev), email client on Windows 11 via UTM 
- Node Version: 22
- Link to reproduction _(⚠️ read below)_: umm this is kind of hard since I don't exactly want to provide keys to our Sendgrid account to actually send the emails here. 

### Expected Behavior
Buttons are links that are clickable on all email clients. Gmail seems fine.

### Actual Behavior
On Outlook (classic), the link isn't actually a button and on click just kind of highlights the button, nor does it show the "hand" cursor on hover

Screenshot 2024-12-24 at 16 03 56

Viewing the source,

Screenshot 2024-12-24 at 16 03 40

we see that there is an `<a>` element, but it doesn't seem to be clickable at all. here's the resulting HTML:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang=3D"en" dir=3D"ltr" xmlns:o=3D"urn:schemas-microsoft-com:office:o=
ffice" xmlns:v=3D"urn:schemas-microsoft-com:vml">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
</head>
<body>
<div style=3D"table-layout:fixed;width:100%">
<div style=3D"margin:0 auto;max-width:600px"><span><!--[if mso]><table alig=
n=3D"center" width=3D"600" style=3D"border-spacing: 0; width:600px;" role=
=3D"presentation"><tr><td><![endif]--></span>
<table align=3D"center" width=3D"100%" role=3D"presentation" cellspacing=3D=
"0" cellpadding=3D"0" border=3D"0" style=3D"max-width:600px">
<tbody>
<tr style=3D"width:100%">
<td align=3D"center">
<table width=3D"100%" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border-collapse:collapse" role=3D"presentation">
<tbody>
<tr>
<td align=3D"left"><span><!--[if mso]>
            <v:roundrect xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:w=
=3D"urn:schemas-microsoft-com:office:word" style=3D"height:50px;v-text-anch=
or:middle;width:200px;" arcsize=3D"0%"  strokeweight=3D"1px" fill=3D"false"=
>
            <w:anchorlock/>
            <center style=3D"font-size:16px;">
            Sign In By Clicking Here
            </center></v:roundrect>
            <![endif]--></span><a href=3D"https://url8612.email.breezehr.co=
m/ls/click?upn=3Du001.5pi1QUNK2POq-2BylfXxKg2TbOJCo60TlC-2BlezPvYAQr2M-2Bzk=
JF3p65auafFgxaPxQAyqp-2Fk-2F3USOHF4sWuvkL57gX575XUVg7fLTyoyhF5qYnNVbYAIgl4l=
zjilYcLI34Q1mBMtSwvcR5Fc1xLZpGBpXE1lC96ToX3oW-2FZuVYvi1DrInK-2B4gKMjTo-2B7C=
WMopRAC-2BrUJneF4k8mB-2FoN77v9A-3D-3DBTxe_1TlFHJk1nIIvI0ll4srvpKrX2ZZejd29L=
pCFDe5n2TLJL8WArQKowx5ZgGoB-2FVgQytdcDE-2B5-2F2LrvzqE-2B2-2BA0AFBoW32-2FrOw=
2jIb3qqGbLtY5hWmxsX88RQq2bMtPOVfOT35-2BHxNRsXBev3pfjMxL9eHdSiW0vVZSwtY0moLI=
PvnetjkcTkVCAopC9b5bY-2Bthh-2FC1rNiHrv3YZaDpPpO2f8wDup08ulgehq1-2FkiWtmg-3D=
" style=3D"-webkit-text-size-adjust:none;border-radius:0;display:inline-blo=
ck;font-size:16px;line-height:48px;max-width:200px;text-align:center;text-d=
ecoration:none;width:100%;mso-hide:all">Sign
 In By Clicking Here</a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<span><!--[if mso]></td></tr></table><![endif]--></span></div>
</div>
</body>
</html>
```

### Additional Information

Maybe relevant but I'm using React 19 in the server, despite `jsx-email` not officially supporting it.

### PR DESCRIPTION
**Pull request by osdiab**
## Component / Package Name:

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, please include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.

List any relevant issue numbers:

resolves #272 

### Description

Something like this should fix that issue. based off of what I found from this random tutorial online. https://www.nobledesktop.com/learn/html-email/bulletproof-buttons-in-outlook

### CODE REVIEW

File: packages/jsx-email/src/components/button.tsx [hunk 1]
```diff
@@ -83,6 +85,20 @@ export const Button: JsxEmailComponent<ButtonProps> = ({
...
     </a>
   );
+  const vmlFallbackLinkContents = (
+    <a
+      rel={rel}
+      href={href}
+      style={{
+        color: textColor,
+        ...baseStyles,
+        ...style
```
Comment (osdiab) [inline packages/jsx-email/src/components/button.tsx:95]: weird things can happen with `style` here but not sure how one would tease it out otherwise.

File: packages/jsx-email/src/components/button.tsx [hunk 2]
```diff
@@ -83,6 +85,20 @@ export const Button: JsxEmailComponent<ButtonProps> = ({
       {children}
     </a>
   );
+  const vmlFallbackLinkContents = (
+    <a
+      rel={rel}
+      href={href}
+      style={{
+        color: textColor,
+        ...baseStyles,
```
Comment (osdiab) [inline packages/jsx-email/src/components/button.tsx:94]: probably don't need all the base styles but didn't seem like it would hurt? can pick out the relevant ones though

File: packages/jsx-email/src/components/button.tsx [hunk 3]
```diff
@@ -32,6 +32,7 @@ export const Button: JsxEmailComponent<ButtonProps> = ({
   fontSize = 16,
   align = 'left',
   withBackground = false,
+  rel,
```
Comment (osdiab) [inline packages/jsx-email/src/components/button.tsx:35]: explicitly picked out `rel` since we do need to throw those onto the VML element too

File: packages/jsx-email/src/components/button.tsx [hunk 4]
```diff
@@ -101,14 +117,16 @@ export const Button: JsxEmailComponent<ButtonProps> = ({
...
+              rel ? `rel="${rel}" ` : ''
+            }href="${href}" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" style="height:${height}px;v-text-anchor:middle;width:${width}px;" arcsize="${arcsize}%" ${
                   borderColor ? `strokecolor=${borderColor}` : ''
                 } ${borderSize ? `strokeweight="${borderSize}px"` : `stroke="false"`} ${
                   backgroundColor ? `fillcolor=${backgroundColor}` : `fill="false"`
                 }>
             <w:anchorlock/>
             <center style="font-size:${fontSize}px;${textColor ? `color:${textColor};` : ''}">
-            ${children}
+            ${vmlFallbackLinkContents}
```
Comment (osdiab) [inline packages/jsx-email/src/components/button.tsx:129]: I have never interpolated a `ReactNode` into a string like is done with `children` here but I assume that pattern works given that this is what already was here.

**Review by osdiab — COMMENTED** [review]
I don't know how to actually run this locally to send a real email out to see how it turns out but based on my manual experiments messing around with the output on my existing codebase, something like this should work.

**Comment by lordelogos** [comment]
Hi @osdiab, 

Thank you for this PR—it helped me identify an oversight related to the href prop in the VML button implementation.

The current VML button is based on the bullet proof email button by [Stigm](https://twitter.com/stigm/)
Upon reviewing your code and investigating the issue in the existing component, I discovered that the `v:roundrect` element is missing the `href` prop, which is the root cause of the problem.

```tsx
  <v:roundrect href={href} ...>
```

Would you like to address this in your PR, or should I go ahead and make the necessary changes?

Looking forward to your thoughts!
